### ISSUE TITLE
When deploying parse server to heroku, how do I update / pull the latest parse server code?

### ISSUE THREAD

**Issue by a9austin** [ParsePlatform/parse-server-example#104]
I am not sure if I understand how the deployment process works. I have used the purple "deploy to heroku" button, but I was wondering if I want to update the parse server to the latest code, how would I do that? 

Thanks in advance.

**Comment by raginggoat** [comment]
I'm wondering the same thing for my Ubuntu 14.04 droplet on Digital Ocean.

**Comment by luchiolb** [comment]
Hey @a9austin, 
Heroku let's you manually re-deploy the code from your **own** repo in Git. 
So, in order to do that, you'll need to fork the server-example repo in Git to be able to use it in Heroku, and then you can update your fork with the original parse-server-example repo changes and deploy it to Heroku when you consider necessary.
I imagine you can do the same for Digital Ocean @raginggoat.

**Comment by gfosco** [comment]
You can clone your heroku instance, and re-deploy, which should pull down the latest dependencies.  You can also update package.json to a specific version number.  We're releasing 2.2 soon, and we'll be updating the example project too.

**Comment by a9austin** [comment]
Thank you for the response @luchiolb .

When ever I call git clone my heroku code, I don't see the 'server-example' code. I only see the 'parse-server-example' code. I am having troubles understanding where exactly I merge the server-example fork when I do not have that code on heroku? I might be misunderstanding the process.
