### ISSUE TITLE
Parse Server Shutting Down Frequently

### ISSUE THREAD

**Issue by mike3osei** [ParsePlatform/parse-server-example#187]
After updating my parse server from 2.1.4 on Azure it seems that there is an issue with up-time. Frequently, my parse server is down. Every time it is down I can temporarily fix it by restarting the server at index.js and then everything works fine, however, after 5 minutes it shuts down again. Any ideas on how this issue could be resolved?

**Comment by drew-gross** [comment]
This could be any number of issues. Can you check the memory usage of the Parse Server? It might be running out of memory. It also might be caused by errors in your Cloud Code, so can you check your server logs to see if there are a lot of failing requests? Use the `verbose: true` option in your server settings, or the `VERBOSE=1` environment variable.

**Comment by mike3osei** [comment]
From looking into it a bit more, it seems it may be an issue with DocumentDb. They are working on a fix at the moment. I'll keep this feed posted when the issue is resolved.

**Comment by mike3osei** [comment]
They missed this documentDb issue. All is well.
