### ISSUE TITLE
Heroku Creates Empty Repo

### ISSUE THREAD

**Issue by jamesjackson69** [ParsePlatform/parse-server-example#201]
I used the deploy with Heroku button and I can open the app and see _Make sure to star the parse-server repo on GitHub!_ but when I $ heroku git:clone -a myApp it says 

```
my-mac:~ me$  heroku git:clone -a myApp
Cloning into 'myApp'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
```
and the directory is empy.

**Comment by zualas** [comment]
Check an[ answer at Stackoverflow](http://stackoverflow.com/questions/36621955/heroku-clone-creates-an-empty-folder/37497276#37497276), it might help:

**Comment by brennanMKE** [comment]
I did not find the previously linked answer on SO to help while the following page did. I hope it helps others who are experiencing the same problem.

https://kb.heroku.com/why-do-i-see-a-message-you-appear-to-have-cloned-an-empty-repository

What was not clear to me, and appears to be an issue for others, is that by using the Install on Heroku button the current GitHub repository is used to deploy the app on Heroku but when using the command below it results in an empty repository. Part of the problem is that the origin needs to be defined so that when Git pulls from the origin there is something there. For whatever reason the Heroku CLI does not pull the files from the original repository and it results in an empty repository.

`heroku git:clone -a my-parse-app`

What I did not do from the start was fork the original repository before installing the app on Heroku. I created a fork and then used that URL for the following command.

`git remote add origin https://github.com/USERNAME/parse-server-example`

With a remote defined for the origin I can then use the following command.

`git pull origin master`

Now I should be able to deploy from this folder with the Heroku CLI.

**Comment by kendrikat** [comment]
Another solution for the impatient:

```
git clone git@github.com:ParsePlatform/parse-server-example.git your-app-name
cd your-app-name
git remote add heroku https://git.heroku.com/your-app-name.git
```

http://stackoverflow.com/a/41209906/1257369
